
class McpePacketIds:
    NEW_LOGIN = 0x01
    NEW_BATCH = 0x06
    NEW_TEXT = 0x07
    NEW_ADD_ENTITY = 0x0b
    NEW_REMOVE_ENTITY = 0x0c
    NEW_MOVE_ENTITY = 0x0f
    NEW_MOVE_PLAYER = 0x10
    NEW_REMOVE_BLOCK = 0x12
    NEW_UPDATE_BLOCK = 0x13
    NEW_SET_ENTITY_MOTION = 0x23
    NEW_MOB_EQUIPMENT = 0x1b
    NEW_MOB_ARMOR_EQUIPMENT = 0x1c
    NEW_INTERACT = 0x1e
    NEW_USE_ITEM = 0x1f
    NEW_PLAYER_ACTION = 0x20
    NEW_ANIMATE = 0x27
    NEW_CONTAINER_SET_SLOT = 0x2c
    NEW_PLAYER_LIST = 0x38
    NEW_REQUEST_CHUNK_RADIUS = 0x3d

    OLD_LOGIN = 0x8f
    OLD_BATCH = 0x92
    OLD_TEXT = 0x93
    OLD_REMOVE_PLAYER = 0x97
    OLD_ADD_ENTITY = 0x98
    OLD_MOVE_ENTITY = 0x9c
    OLD_UPDATE_BLOCK = 0x9f
    OLD_SET_ENTITY_MOTION = 0xae
